accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout")
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
   path('', views.home, name="home"),
   path('details/<int:id>/', views.detail, name="detail"),
   path('addmovies/', views.add_movies, name="add_movies"),
   path('addreview/<int:id>/', views.add_review, name="add_review")
   
]

moviereview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Movie(models.Model):
    #field  for the movie table
    name = models.CharField(max_length=300)
    director = models.CharField(max_length=300)
    cast = models.CharField(max_length=300)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    averagerating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Review(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username
        


accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    class meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'password2') 

main/forms.py
from django import forms
from .models import *

#movie add form
class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'director', 'cast', 'description', 'release_date', 'image')

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("comment", "rating")      

accounts/views.py
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth import authenticate, login, logout

# Create your views here.
#registration
def register(request):
    if request.user.is_authenticated:
        return redirect("main:home")

    else:
         if request.method == "POST":
            form = RegistrationForm(request.POST or None)
        #check if form is valid
            if form.is_valid():
                User = form.save()

            #get the raw password
                raw_password = form.cleaned_data.get('password1')

            #authenticate the user
                User = authenticate(username=User.username, password=raw_password)

            #login the user
                login(request, User)

                return redirect("main:home")

         else:
            form = RegistrationForm()
         return render(request, "accounts/register.html", {"form": form})
               

#Login
def login_user(request):
    if request.user.is_authenticated:
        return redirect("main:home")
    else:    
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']

            print(username, password)

        #check the credential
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect("main:home")
                else:
                    return render(request, 'accounts/login.html', {"error": "your account has been disable."})
            else:
                return render(request, 'accounts/login.html',{"error":"invalis username or password"})
        return render(request, 'accounts/login.html')

#logout
def logout_user(request):
    if request.user.is_authenticated:
        logout(request)
        print("logged out succesfully")
        return redirect("accounts:login")    
    else:
        return redirect("accounts:login")                            


main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.
def home(request):
    query = request.GET.get("title")
    allMovies = None
    if query:
        allMovies = Movie.objects.filter(name__icontains=query)
    else:    
        allMovies = Movie.objects.all()
        print('allMovies')

    context = {
        "movies":allMovies,
    }

    return render(request, 'main/index.html', context)

#detail page
def detail(request, id):
    movie = Movie.objects.get(id=id)  #select * from where id-id
    reviews = Review.objects.filter(movie=id).order_by("-comment")
    context={
        "movie":movie,
        "reviews":reviews
    }

    return render(request, 'main/details.html', context)


#add movie to the database

def add_movies(request):
    if request.method == "POST":
        form = MovieForm(request.POST or None)

        #check if form is valid
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return redirect("main:home")

    else:
         form = MovieForm()
    return render(request, 'main/addmovies.html', {"form":form})    

def add_review(request, id):
    if request.user.is_authenticated:
        movie = Movie.objects.get(id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.movie = movie
                data.save()
                return redirect("main:detail", id)

        else:
            form = ReviewForm()
        return render(request, 'main/details.html', {"form": form})
    else:
        return redirect("accounts:login")


accounts/templates/accounts/login.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Login to your account</h3>
            <form action="", method="POST">
                {% csrf_token %}
                <label for="username">Username</label>
                <input type="text" placeholder="Enter your username" class="form-control" name="username">

                <label for="password">Password</label>
                <input type="text" placeholder="Enter your password" class="form-control" name="password">
                <br>
                {% if error %}
                    <i style="color:aquamarine">{{ error }}</i>
                {% endif %}    
                <input type="submit" value="Login" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'main/base.html' %}



{% block content %}

 <div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Register an Account</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p  }}
                <input type="submit" value="Register" class="btn btn-danger">
            </form>
        </div>
    </div>
 </div>

{% endblock %}

main/templates/main/addmovies.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-content">
            <h3 class="text-center">Add Movie</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Add Movies">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>Moviereview</title>

    
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a class="navbar-brand" href="{% url 'main:home' %}">Movie Review</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:add_movies' %}">Add Movie</a>
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">My Profile</a>
               
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
              </div>
            </li>
            {% else %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%  url 'accounts:register' %}">Register</a>
            </li>


            {% endif %}
         
          </ul>
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'main:home' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/details.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <br>
  <div class="card">
      <div class="card-body">
      <div class="row">
          <div class="col-md-4">
             <img src="{{ movie.image }}" alt="{{ movie.name}}" class="img-fluid">
          </div>
          <div class="col-md-8">
              <h3 class="text-center">
                  {{ movie.name }}
              </h3>
              <p>{{ movie.description }}</p>
              <h5>Director: {{ movie.director }}</h5>
              <h5>Cast: {{ movie.cast }}</h5>
              <h5>Rating: {{ movie.averagerating }}</h5>
          </div>
      </div>
      </div>
  </div>

  <br>
  <div class="card">
      <div class="card-body">
          <h3 class="text-center">Add Reviews</h3>
          <form action="{% url 'main:add_review' movie.id %}" method="POST">
            {% csrf_token %}
            <label for="comment">Review</label>
            <textarea name="comment" id="comment" cols="30" rows="5" class="form-control" ></textarea>

            <label for="rating">Rating</label>
            <input type="text" name="rating" class="form-control">

            <br>
            <input type="submit" class="btn btn-danger" value="Add Review">
          </form>
      </div>
  </div>
  <br> 
  <div class="card">
      <div class="card-body">
          <h3 class="text-center">Reviews</h3>
          {% for review in reviews %}
             <div class="card" style="background-color: #f5eeee">
                 <div class="card-body">
                     <div class="row">
                         <div class="col-md-3">
                             <h5 class="text-left">{{ review.user.username }}</h5>
                             <h5>{{ review.rating }}</h5>
                         </div>
                         <div class="col-md-9">
                              <p>{{ review.comment }}</p>
                         </div>    
                     </div>
                 </div>
             </div>
             <br>
             {% endfor %}
      </div>
  </div>
</div>



{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}


{% block content %}

<div class="container">
    <br>
    <div class="card" id="backdrop">
        <div class="card-body">
            <div class="row">
                {% for movie in movies %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                        <div class="text-center">
                        <img src="{{ movie.image }}" alt="" class="img-fluid" width="70%">
                        <h3 class="text-center">{{ movie.name }}</h3>
                        
                        <i class="text-center">{{ movie.release_date }}</i>
                        <a href="{% url 'main:detail' movie.id %}">Read More</a>
                    </div>
                    </div>
                    </div>

                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>


{% endblock %}